const OverlayType = {
  CUSTOM_BILLBOARD: 'custom_billboard',
  CUSTOM_LABEL: 'custom_label',
  BILLBOARD: 'billboard',
  BOX: 'box',
  CIRCLE: 'circle',
  CORRIDOR: 'corridor',
  CYLINDER: 'cylinder',
  DIV_ICON: 'div_icon',
  ELLIPSE: 'ellipse',
  ELLIPSOID: 'ellipsoid',
  LABEL: 'label',
  PLANE: 'plane',
  POINT: 'point',
  POLYLINE: 'polyline',
  POLYGON: 'polygon',
  POLYLINE_VOLUME: 'polyline_volume',
  RECTANGLE: 'rectangle',
  WALL: 'wall',
  MODEL: 'model',
  TILESET: 'tileset',
  ATTACK_ARROW: 'attack_arrow',
  DOUBLE_ARROW: 'double_arrow',
  FINE_ARROW: 'fine_arrow',
  GATHERING_PLACE: 'gathering_place',
  TRAILED_ATTACK_ARROW: 'tailed_attack_arrow',
  ELEC_ELLIPSOID_PRIMITIVE: 'elec_ellipsoid_primitive',
  FLOW_LINE_PRIMITIVE: 'flow_line_primitive',
  SCAN_CIRCLE_PRIMITIVE: 'scan_circle_primitive',
  TRAIL_LINE_PRIMITIVE: 'trail_line_primitive',
  VIDEO_PRIMITIVE: 'video_primitive',
  WATER_PRIMITIVE: 'water_primitive'
}

export default OverlayType
